ALTER TABLE materials ADD COLUMN pathogen_type VARCHAR(100);
ALTER TABLE materials ADD COLUMN status VARCHAR(50) DEFAULT 'DRAFT' NOT NULL;
ALTER TABLE materials ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
